<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace PWCode\eBaySDK\Test\ProductMetadata\Types;

use PWCode\eBaySDK\ProductMetadata\Types\GetProductSearchValuesBulkResponse;

class GetProductSearchValuesBulkResponseTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new GetProductSearchValuesBulkResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\PWCode\eBaySDK\ProductMetadata\Types\GetProductSearchValuesBulkResponse', $this->obj);
    }

    public function testExtendsGetProductSearchValuesResponse()
    {
        $this->assertInstanceOf('\PWCode\eBaySDK\ProductMetadata\Types\GetProductSearchValuesResponse', $this->obj);
    }
}
