<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace PWCode\eBaySDK\Test\RelatedItemsManagement\Types;

use PWCode\eBaySDK\RelatedItemsManagement\Types\DeleteBundlesRequest;

class DeleteBundlesRequestTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new DeleteBundlesRequest();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\PWCode\eBaySDK\RelatedItemsManagement\Types\DeleteBundlesRequest', $this->obj);
    }

    public function testExtendsBaseRequest()
    {
        $this->assertInstanceOf('\PWCode\eBaySDK\RelatedItemsManagement\Types\BaseRequest', $this->obj);
    }
}
