<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace PWCode\eBaySDK\Test\Marketing\Types;

use PWCode\eBaySDK\Marketing\Types\CreateAdsByInventoryReferenceRestResponse;

class CreateAdsByInventoryReferenceRestResponseTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new CreateAdsByInventoryReferenceRestResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\PWCode\eBaySDK\Marketing\Types\CreateAdsByInventoryReferenceRestResponse', $this->obj);
    }

    public function testExtendsAdReferences()
    {
        $this->assertInstanceOf('\PWCode\eBaySDK\Marketing\Types\AdReferences', $this->obj);
    }
}
