<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace PWCode\eBaySDK\Test\Marketing\Types;

use PWCode\eBaySDK\Marketing\Types\GetItemPromotionRestResponse;

class GetItemPromotionRestResponseTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new GetItemPromotionRestResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\PWCode\eBaySDK\Marketing\Types\GetItemPromotionRestResponse', $this->obj);
    }

    public function testExtendsItemPromotionResponse()
    {
        $this->assertInstanceOf('\PWCode\eBaySDK\Marketing\Types\ItemPromotionResponse', $this->obj);
    }
}
