<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace PWCode\eBaySDK\Test\Marketing\Types;

use PWCode\eBaySDK\Marketing\Types\GetListingsInSpecificPromotionRestResponse;

class GetListingsInSpecificPromotionRestResponseTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new GetListingsInSpecificPromotionRestResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\PWCode\eBaySDK\Marketing\Types\GetListingsInSpecificPromotionRestResponse', $this->obj);
    }

    public function testExtendsItemsPagedCollection()
    {
        $this->assertInstanceOf('\PWCode\eBaySDK\Marketing\Types\ItemsPagedCollection', $this->obj);
    }
}
