<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace PWCode\eBaySDK\Test\Taxonomy\Types;

use PWCode\eBaySDK\Taxonomy\Types\GetSuggestedCategoriesRestResponse;

class GetSuggestedCategoriesRestResponseTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new GetSuggestedCategoriesRestResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\PWCode\eBaySDK\Taxonomy\Types\GetSuggestedCategoriesRestResponse', $this->obj);
    }

    public function testExtendsCategorySuggestionResponse()
    {
        $this->assertInstanceOf('\PWCode\eBaySDK\Taxonomy\Types\CategorySuggestionResponse', $this->obj);
    }
}
