<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace PWCode\eBaySDK\Test\Inventory\Types;

use PWCode\eBaySDK\Inventory\Types\GetInventoryItemsRestResponse;

class GetInventoryItemsRestResponseTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new GetInventoryItemsRestResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\PWCode\eBaySDK\Inventory\Types\GetInventoryItemsRestResponse', $this->obj);
    }

    public function testExtendsInventoryItems()
    {
        $this->assertInstanceOf('\PWCode\eBaySDK\Inventory\Types\InventoryItems', $this->obj);
    }
}
