<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace PWCode\eBaySDK\Test\Fulfillment\Enums;

use PWCode\eBaySDK\Fulfillment\Enums\OrderFulfillmentStatus;

class OrderFulfillmentStatusTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new OrderFulfillmentStatus();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\PWCode\eBaySDK\Fulfillment\Enums\OrderFulfillmentStatus', $this->obj);
    }
}
