<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace PWCode\eBaySDK\Test\Account\Types;

use PWCode\eBaySDK\Account\Types\GetAllSalesTaxTablesRestResponse;

class GetAllSalesTaxTablesRestResponseTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new GetAllSalesTaxTablesRestResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\PWCode\eBaySDK\Account\Types\GetAllSalesTaxTablesRestResponse', $this->obj);
    }

    public function testExtendsSalesTaxes()
    {
        $this->assertInstanceOf('\PWCode\eBaySDK\Account\Types\SalesTaxes', $this->obj);
    }
}
