<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace PWCode\eBaySDK\Test\Account\Types;

use PWCode\eBaySDK\Account\Types\GetAPaymentPolicyByIDRestResponse;

class GetAPaymentPolicyByIDRestResponseTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new GetAPaymentPolicyByIDRestResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\PWCode\eBaySDK\Account\Types\GetAPaymentPolicyByIDRestResponse', $this->obj);
    }

    public function testExtendsPaymentPolicy()
    {
        $this->assertInstanceOf('\PWCode\eBaySDK\Account\Types\PaymentPolicy', $this->obj);
    }
}
