<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace PWCode\eBaySDK\Test\Account\Types;

use PWCode\eBaySDK\Account\Types\GetShippingRateTablesRestResponse;

class GetShippingRateTablesRestResponseTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new GetShippingRateTablesRestResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\PWCode\eBaySDK\Account\Types\GetShippingRateTablesRestResponse', $this->obj);
    }

    public function testExtendsRateTableResponse()
    {
        $this->assertInstanceOf('\PWCode\eBaySDK\Account\Types\RateTableResponse', $this->obj);
    }
}
