<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace PWCode\eBaySDK\MerchantData\Types;

/**
 *
 * @property \PWCode\eBaySDK\MerchantData\Types\PaymentInformationType $Payments
 * @property \PWCode\eBaySDK\MerchantData\Types\RefundInformationType $Refunds
 */
class PaymentsInformationType extends \PWCode\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'Payments' => [
            'type' => 'PWCode\eBaySDK\MerchantData\Types\PaymentInformationType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Payments'
        ],
        'Refunds' => [
            'type' => 'PWCode\eBaySDK\MerchantData\Types\RefundInformationType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'Refunds'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
